name: Continuous Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  buildAndTest:
    name: Deploy on Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        if: github.event.pull_request.merged == true
        run: yarn

      - name: Build
        if: github.event.pull_request.merged == true
        run: yarn build

      - name: Deploy
        if: github.event.pull_request.merged == true
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master # deploying branch
